import { NextRequest, NextResponse } from "next/server";
import driver from "@/lib/neo4j";
import { generateCypherFromQuestion } from "@/services/graphrag/generateCypher";
import {
  AskGraphSchema,
  GraphRagResponseSchema,
  SimpleGraphResultSchema,
} from "@/types/graphrag";

const KNOWN_WORDS = ["kabar", "kursi", "kantor", "gereja", "agama"];

function detectWordFromQuestion(question: string): string | null {
  const normalized = question.toLowerCase();

  for (const word of KNOWN_WORDS) {
    if (normalized.includes(word)) {
      return word;
    }
  }

  return null;
}

export async function GET() {
  const session = driver.session();

  try {
    const result = await session.run("RETURN 'Neo4j connected' AS message");
    const message = result.records[0]?.get("message");

    return NextResponse.json({
      ok: true,
      message,
    });
  } catch (error) {
    console.error("Neo4j connection error:", error);

    return NextResponse.json(
      {
        ok: false,
        error: "Failed to connect to Neo4j Aura",
      },
      { status: 500 }
    );
  } finally {
    await session.close();
  }
}

export async function POST(req: NextRequest) {
  const session = driver.session();
  const logs: string[] = [];

  try {
    logs.push("Request received");

    const body = await req.json();
    const parsed = AskGraphSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        {
          ok: false,
          error: "Request tidak valid",
          details: parsed.error.flatten(),
        },
        { status: 400 }
      );
    }

    logs.push("Request validated with Zod");

    const question = parsed.data.question;
    const detectedWord = detectWordFromQuestion(question);

    logs.push(`Detected word: ${detectedWord ?? "none"}`);

    if (!detectedWord) {
      const payload = GraphRagResponseSchema.parse({
        ok: true,
        question,
        detectedWord: null,
        cypher: null,
        answer:
          "Saya belum menemukan kata yang dikenali di pertanyaan. Coba gunakan salah satu kata contoh seperti kabar, kursi, kantor, gereja, atau agama.",
        records: [],
        logs,
      });

      return NextResponse.json(payload);
    }

    let cypher: string | null = null;

    try {
      cypher = await generateCypherFromQuestion(question);
      logs.push("Cypher generated by OpenRouter");
      logs.push(`Cypher: ${cypher}`);
    } catch (error) {
      console.error("OpenRouter generation failed:", error);

      logs.push("OpenRouter failed, fallback to static Cypher");

      cypher = `
        MATCH (w:Word {lemma: $lemma})-[:ORIGIN_LANGUAGE]->(l:Language)
        RETURN w.lemma AS word, l.name AS origin_language
        LIMIT 1
      `.trim();

      logs.push(`Fallback Cypher: ${cypher}`);
    }

    const result = await session.run(cypher, {
      lemma: detectedWord,
    });

    logs.push(`Neo4j query executed, records: ${result.records.length}`);

    const records = result.records.map((record) =>
      SimpleGraphResultSchema.parse({
        word: record.get("word"),
        origin_language: record.get("origin_language"),
      })
    );

    let answer = `Data untuk kata "${detectedWord}" tidak ditemukan.`;

    if (records.length > 0) {
      answer = `Kata "${records[0].word}" berasal dari bahasa ${records[0].origin_language}.`;
      logs.push("Answer generated from Neo4j result");
    } else {
      logs.push("No matching data found in Neo4j");
    }

    const payload = GraphRagResponseSchema.parse({
      ok: true,
      question,
      detectedWord,
      cypher,
      answer,
      records,
      logs,
    });

    return NextResponse.json(payload);
  } catch (error) {
    console.error("POST /api/graphrag error:", error);

    return NextResponse.json(
      {
        ok: false,
        error: "Terjadi kesalahan pada server",
        logs,
      },
      { status: 500 }
    );
  } finally {
    await session.close();
  }
}